# Generated by Django 4.2.7 on 2023-12-09 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=25, verbose_name='Server')),
                ('gamemode', models.CharField(max_length=25, verbose_name='Gamemode')),
                ('total_players', models.IntegerField(verbose_name='total players')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Player Name')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.groups')),
            ],
        ),
    ]
