# Generated by Django 4.2.7 on 2023-12-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='discord',
            field=models.CharField(max_length=70, null=True, verbose_name='discord'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='gamemode',
            field=models.CharField(max_length=25, verbose_name='gamemode'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='server',
            field=models.CharField(max_length=25, verbose_name='server'),
        ),
    ]
