# Generated by Django 4.2.7 on 2023-12-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_groups_discord_alter_groups_gamemode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreePlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=25, verbose_name='server')),
                ('gamemode', models.CharField(max_length=25, verbose_name='gamemode')),
                ('nickname', models.CharField(max_length=25, verbose_name='nickname')),
                ('discord', models.CharField(max_length=70, null=True, verbose_name='discord')),
            ],
        ),
        migrations.RenameModel(
            old_name='Players',
            new_name='GroupPlayers',
        ),
    ]
