# Generated by Django 4.2.7 on 2023-12-10 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_freeplayers_rename_players_groupplayers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='total_players',
        ),
        migrations.AddField(
            model_name='groups',
            name='player_name1',
            field=models.CharField(max_length=25, null=True, verbose_name='Player 1 Name'),
        ),
        migrations.AddField(
            model_name='groups',
            name='player_name2',
            field=models.CharField(max_length=25, null=True, verbose_name='Player 2 Name'),
        ),
        migrations.AddField(
            model_name='groups',
            name='player_name3',
            field=models.CharField(max_length=25, null=True, verbose_name='Player 3 Name'),
        ),
        migrations.AddField(
            model_name='groups',
            name='player_name4',
            field=models.CharField(max_length=25, null=True, verbose_name='Player 4 Name'),
        ),
        migrations.DeleteModel(
            name='GroupPlayers',
        ),
    ]
