# Generated by Django 4.2.7 on 2023-12-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_groups_total_players_groups_player_name1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='player_name1',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Player 1 Name'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='player_name2',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Player 2 Name'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='player_name3',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Player 3 Name'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='player_name4',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Player 4 Name'),
        ),
    ]
